<a href="https://colab.research.google.com/github/ahmadayoubi404/Deep-Learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tensor_0d = tf.constant(4)
print(tensor_0d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_1d = tf.constant([2, 0, -3])
print(tensor_1d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_3d = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor_3d)
print("shape = " + str(tensor_3d.shape))
print("dimension = " + str(tensor_3d.ndim))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 3, 3), dtype=int32)
shape = (2, 3, 3)
dimension = 3


In [ ]:
tensor_4d = tf.constant([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]], [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]])
print(tensor_4d)
print("shape = " + str(tensor_4d.shape))
print("dimension = " + str(tensor_4d.ndim))

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]], shape=(2, 2, 3, 3), dtype=int32)
shape = (2, 2, 3, 3)
dimension = 4


In [ ]:
tensor_1d = tf.constant([2, 0, -3], dtype = tf.float16)
print(tensor_1d)

casted_tensor = tf.cast(tensor_1d, dtype = tf.int16) #if we casted as dtype = tf.bool then everything would be True but 0 would be False
print(casted_tensor)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float16)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int16)


In [ ]:
#numpy array to tensor
import numpy as np
np_array = np.array([1, 2, 3])
print(np_array)
tensor = tf.convert_to_tensor(np_array)
print(tensor)

[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
#identity matrix
eye_tensor = tf.eye(num_rows=3, num_columns=4, dtype=tf.dtypes.float32, name=None)
print(eye_tensor)
print(3 * eye_tensor)

#making it boolean
eye_tensor = tf.eye(num_rows=3, num_columns=None, dtype=tf.dtypes.bool, name=None)
print(eye_tensor)

#making it 3d
eye_tensor = tf.eye(num_rows=3, num_columns=None, batch_shape=[3, ], dtype=tf.dtypes.float32, name=None)
print(eye_tensor)

#making it 4d
eye_tensor = tf.eye(num_rows=3, num_columns=None, batch_shape=[3, 2], dtype=tf.dtypes.float32, name=None)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)
tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(3, 2, 3, 3), dtype=float32)


In [ ]:
#filling
tensor = tf.fill([3, 4], 5, name = None) #2d tensor
print(tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
tensor = tf.ones([3, 4, 5]) #3d tensor
print(tensor)

tensor = tf.zeros([3, 4, 5]) #3d tensor
print(tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [ ]:
tensor = tf.ones_like([3, 4, 5]) #it prints the same shape but with ones
print(tensor)

tensor = tf.ones_like([[1, 2, 3], [4, 5, 6]])
print(tensor)

tensor = tf.zeros_like([[1, 2, 3], [4, 5, 6]]) #it prints the same shape but with zeros
print(tensor)

tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [ ]:
#nb of all scalers/elements
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor)
print(tf.size(tensor))

tensor_3d = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor_3d)
print(tf.size(tensor_3d, out_type=tf.float32))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(18.0, shape=(), dtype=float32)


In [ ]:
#random normal distribution tensors
tensor = tf.random.normal(shape = [3, 2], mean = 0.0, stddev = 1.0, dtype = tf.dtypes.float32)
print(tensor) #the values are around the mean and the stddev are how far the values are from the mean

#random uniform distribution tensors
tensor = tf.random.uniform(shape = [3, 2], minval = 0, maxval = 2, dtype = tf.dtypes.float32)
print(tensor) #the values are around the mean and the stddev are how far the values are from the mean

tf.Tensor(
[[-0.34603527  1.4702682 ]
 [-0.77765864 -1.9972074 ]
 [ 0.79909325 -0.3913589 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.20717788 1.4387419 ]
 [0.1295619  0.11545181]
 [0.18194604 0.21106625]], shape=(3, 2), dtype=float32)


In [ ]:
#indexing
tensor = tf.constant([3, 5, 2, 4, 5, 66, 7])
print(tensor)
print(tensor[4])
print(tensor[0:4])
print(tensor[2:6])
print(tensor[2:6:2]) #step is 2 here but by default it is 1
print(tensor[2:]) #from 2 till the end
print(tensor[2:-1]) #from 2 till the end-1
print(tensor[:]) #all elements

tensor2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor2)
print(tensor2[0:3, 0:2]) #first 3 rows and first 2 columns
print(tensor2[0:3, :]) #first 3 rows and all columns
print(tensor2[1, :]) #row 2 and all columns
print(tensor2[1, 1]) #row 2 and column 2

tensor3 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor3[0,:,:])
print(tensor3[:,0:2,0:2]) #draw the 3d matrix to visualize it

tf.Tensor([ 3  5  2  4  5 66  7], shape=(7,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([3 5 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 2  4  5 66], shape=(4,), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor([ 2  4  5 66  7], shape=(5,), dtype=int32)
tf.Tensor([ 2  4  5 66], shape=(4,), dtype=int32)
tf.Tensor([ 3  5  2  4  5 66  7], shape=(7,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]], shape=(2, 2, 2), dtype=int32)
