<a href="https://colab.research.google.com/github/ahmadayoubi404/Deep-Learning/blob/main/common_tensorflow_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [4]:
# 3d tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor.shape)

#adding an extra axis
print(tf.expand_dims(tensor, axis=0).shape)
print(tf.expand_dims(tensor, axis=1).shape)
print(tf.expand_dims(tensor, axis=2).shape)
print(tf.expand_dims(tensor, axis=-1).shape)

(2, 2, 3)
(1, 2, 2, 3)
(2, 1, 2, 3)
(2, 2, 1, 3)
(2, 2, 3, 1)


In [13]:
# 3d tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor.shape)

#expanded
tensor = tf.expand_dims(tensor, axis=0)
print(tensor.shape)

#squeeze
print(tf.squeeze(tensor).shape)
print(tf.squeeze(tensor, axis = 0).shape) #works
print(tf.squeeze(tensor, axis = 1).shape) #doesn't work because the axis should be 1 here it is 2 same for the other axis

(2, 2, 3)
(1, 2, 2, 3)
(2, 2, 3)
(2, 2, 3)


In [31]:
# 3d tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)

#reshape from 3d tensor to 2d tensor
tensor = tf.reshape(tensor, shape=(2,6))
print(tensor)
print(tensor.shape)

#reshape from 2d tensor to 1d tensor
tensor = tf.reshape(tensor, shape=(12))
print(tensor)
print(tensor.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)
(2, 6)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
(12,)


In [35]:
# 3d tensor
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])
print(t1.shape)
print(t2.shape)

#concat
print(tf.concat([t1,t2], axis=0))
print(tf.concat([t1,t2], axis=1))

#stack
print(tf.stack([t1,t2], axis=0))
print(tf.stack([t1,t2], axis=1))
print(tf.stack([t1,t2], axis=2))



(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]], shape=(2, 3, 2), dtype=int32)


In [40]:
# 3d tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)

#padding
print(tf.pad(tensor, paddings=[[1,1],[1,1],[1,1]]))
print(tf.pad(tensor, paddings=[[1,1],[2,2],[3,3]]))
print(tf.pad(tensor, paddings=[[1,2],[3,4],[5,6]]))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)
tf.Tensor(
[[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  1  2  3  0]
  [ 0  4  5  6  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  7  8  9  0]
  [ 0 10 11 12  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]], shape=(4, 4, 5), dtype=int32)
tf.Tensor(
[[[ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  1  2  3  0  0  0]
  [ 0  0  0  4  5  6  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0]
  [ 0  0  0  7  8  9  0  0  0]
  [ 0  0  0 10 11 12  0  0  0]
  [ 0  0  0  0  0  0  0  0 

In [46]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params[1:4])

print(tf.gather(params, indices=[1, 2, 3]))

print(tf.gather(params, tf.range(1, 4)))

tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)


In [53]:
tensor2d = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tensor2d)
print(tensor2d.shape)

#ragged tensors
raggedtensor = tf.ragged.constant([[1,2,3],[4,5],[7,8,9,10]])
print(raggedtensor)
print(raggedtensor.shape)
print(raggedtensor.to_tensor())

#boolean mask
print(tf.boolean_mask(tensor2d, mask=[True, False, True]))
print(tf.boolean_mask(tensor2d, mask=[[True, False, True],[True, False, True],[True, False, True]]))


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
(3, 3)
<tf.RaggedTensor [[1, 2, 3], [4, 5], [7, 8, 9, 10]]>
(3, None)
tf.Tensor(
[[ 1  2  3  0]
 [ 4  5  0  0]
 [ 7  8  9 10]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)
tf.Tensor([1 3 4 6 7 9], shape=(6,), dtype=int32)


In [56]:
#sparse tensors
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[10, 20],
                                       dense_shape=[3, 4])
print(sparse_tensor)

tf.sparse.to_dense(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[10,  0,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0,  0]], dtype=int32)>

In [59]:
#string tensors
string_tensor = tf.constant(["TensorFlow", "Deep Learning", "AI"])
print(string_tensor)

#join
joined_string_tensor = tf.strings.join(string_tensor, separator=" ")
print(joined_string_tensor)

#split
print(tf.strings.split(joined_string_tensor, sep=" "))

tf.Tensor([b'TensorFlow' b'Deep Learning' b'AI'], shape=(3,), dtype=string)
tf.Tensor(b'TensorFlow Deep Learning AI', shape=(), dtype=string)
tf.Tensor([b'TensorFlow' b'Deep' b'Learning' b'AI'], shape=(4,), dtype=string)


In [63]:
#variables
x = tf.constant([1, 2])
variable = tf.Variable(x)
print(variable)

variable.assign([0, 1])
print(variable)

variable.assign_add([1, 1])
print(variable)

variable.assign_sub([2, 0])
print(variable)



<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 1], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1,  2], dtype=int32)>


In [69]:
with tf.device('CPU:0'):
  x1 = tf.constant([1, 2, 3])
  x2 = tf.constant([4, 5, 6])
with tf.device('GPU:0'):
  x3 = x1 + x2

print(x1, x1.device)
print(x2, x2.device)
print(x3, x3.device)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([4 5 6], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([5 7 9], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
