<a href="https://colab.research.google.com/github/ahmadayoubi404/Deep-Learning/blob/main/Maths_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [13]:
#absolute value
print(tf.abs(tf.constant([-2.25, 3.25])))#it turns the negative into positive
#square root
print(tf.sqrt(tf.constant([1.0, 4.0, 9.0])))
#addition
print(tf.add(tf.constant([1, 2]), tf.constant([3, 4])))
#multiplication
print(tf.multiply(tf.constant([1, 2]), tf.constant([3, 4])))
#substraction
print(tf.subtract(tf.constant([1, 2]), tf.constant([3, 4])))
#division
print(tf.divide(tf.constant([1, 2]), tf.constant([3, 4])))
#division by zero
print(tf.math.divide_no_nan(tf.constant([1, 2]), tf.constant([0, 1])))
#addition with one scalar
print(tf.add(tf.constant([1, 2]), tf.constant(3)))


tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([3 8], shape=(2,), dtype=int32)
tf.Tensor([-2 -2], shape=(2,), dtype=int32)
tf.Tensor([0.33333333 0.5       ], shape=(2,), dtype=float64)
tf.Tensor([0. 2.], shape=(2,), dtype=float64)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [19]:
print(tf.math.maximum(tf.constant([1, 2]), tf.constant([3, 4])))
print(tf.math.minimum(tf.constant([1, 2]), tf.constant([3, 4])))
print(tf.math.equal(tf.constant([1, 2]), tf.constant([3, 4])))
print(tf.math.not_equal(tf.constant([1, 2]), tf.constant([3, 4])))
print(tf.math.less(tf.constant([1, 2]), tf.constant([3, 4])))
print(tf.math.greater(tf.constant([1, 2]), tf.constant([3, 4])))

tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([False False], shape=(2,), dtype=bool)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor([False False], shape=(2,), dtype=bool)


In [29]:
print(tf.math.argmax(tf.constant([1, 2, 3, 4]))) #position of the maximum value
print(tf.math.argmin(tf.constant([[2, 1], [3, 4]]))) #position of the minimum value
print(tf.math.argmin(tf.constant([[2, 1], [3, 4]]), axis = 1)) #position of the minimum value

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([0 0], shape=(2,), dtype=int64)
tf.Tensor([1 0], shape=(2,), dtype=int64)


In [31]:
#power
print(tf.pow(tf.constant([1, 2]), tf.constant([3, 4]))) #1**3 2**4
print(tf.pow(tf.constant([1, 2]), 3)) #1**3 2**3

tf.Tensor([ 1 16], shape=(2,), dtype=int32)
tf.Tensor([1 8], shape=(2,), dtype=int32)


In [41]:
#reduce sum
print(tf.reduce_sum(tf.constant([1, 2, 3, 4])))
print(tf.reduce_sum(tf.constant([[1, 2],[3, 4]]), axis = None))
print(tf.reduce_sum(tf.constant([[1, 2],[3, 4]]), axis = 0))
print(tf.reduce_sum(tf.constant([[1, 2],[3, 4]]), axis = 1))
#reduce min
print(tf.reduce_min(tf.constant([[1, 2],[3, 4]]), axis = 0))
print(tf.reduce_min(tf.constant([[1, 2],[3, 4]]), axis = 1))
#reduce max
print(tf.reduce_max(tf.constant([[1, 2],[3, 4]]), axis = 0))
print(tf.reduce_max(tf.constant([[1, 2],[3, 4]]), axis = 1))
#reduce mean
print(tf.reduce_mean(tf.constant([[1, 2],[3, 4]], dtype = tf.float16), axis = 0))
print(tf.reduce_mean(tf.constant([[1, 2],[3, 4]], dtype = tf.float16), axis = 1))
#reduce standard deviation
print(tf.math.reduce_std(tf.constant([[1, 2],[3, 4]], dtype = tf.float16), axis = 0))
print(tf.math.reduce_std(tf.constant([[1, 2],[3, 4]], dtype = tf.float16), axis = 1))

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([3 7], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([2. 3.], shape=(2,), dtype=float16)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float16)
tf.Tensor([1. 1.], shape=(2,), dtype=float16)
tf.Tensor([0.5 0.5], shape=(2,), dtype=float16)


In [49]:
#top_k
print(tf.math.top_k(tf.constant([1, 2, 3, 4]), k = 2))
print(tf.math.top_k(tf.constant([[1, 2, 3, 4],[5, 6, 7, 8]]), k = 2)) #the top_k matrix and its position matrix

TopKV2(values=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>, indices=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>)
TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [8, 7]], dtype=int32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [3, 2]], dtype=int32)>)


In [56]:
#matrix multiplication
print(tf.matmul(tf.constant([[1, 2],[3, 4]]), tf.constant([[5, 6],[7, 8]])))
#matrix transpose
print(tf.transpose(tf.constant([[1, 2],[3, 4]])))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [69]:
#sparse tensors
sparse_tensor = tf.sparse.SparseTensor(indices = [[0, 0], [1, 2]], values = [1, 2], dense_shape = [3, 4]) #most elements are zeros
print(sparse_tensor)

#diagnol tensor
print(tf.linalg.diag([1, 2, 3]))

#determinant
print(tf.linalg.det(tf.constant([[1, 2],[3, 4]],dtype = tf.float32)))

#inverse
print(tf.linalg.inv(tf.constant([[1, 2],[3, 4]],dtype = tf.float32)))

#trace
print(tf.linalg.trace(tf.constant([[1, 2],[3, 4]],dtype = tf.float32)))

#svd
print(tf.linalg.svd(tf.constant([[1, 2],[3, 4]],dtype = tf.float32)))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), dtype=int32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.4649854 , 0.36596614], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.4045535, -0.9145143],
       [ 0.9145143,  0.4045535]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5760484,  0.8174156],
       [ 0.8174156, -0.5760484]], dtype=float32)>)


In [72]:
import numpy as np

Q = np.random.randn(32, 64, 512) #bqm
K = np.random.randn(32, 128, 512) #bkm #we use the transpose of K

np.einsum('bqm,bkm->bqk', Q, K).shape


(32, 64, 128)

In [76]:
A = np.random.randn(2, 4, 4, 2) #bcij
B = np.random.randn(2, 4, 4, 1) #bcik

np.einsum('bcik,bcij->bckj', B, A).shape

(2, 4, 1, 2)

In [77]:
np.matmul(np.transpose(B, (0, 1, 3, 2)), A).shape

(2, 4, 1, 2)